name: TXD Converter

on: 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install --upgrade pyinstaller
        pip install Pillow
    - name: Build executable
      run: |
        pyinstaller --onefile --name "TXD Converter" --noconsole ./main.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TXD_Converter_Release
        path: "dist/TXD Converter.exe"
    - name: Zip archive
      uses: vimtor/action-zip@v1
      with:
          files: |
            ./README.md
            dist/*.exe
          dest: Release.zip
    - name: Release build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Latest"
        prerelease: false
        title: "Release Build"
        files: |
          Release.zip
        
